# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Okctl < Formula
  desc "Command-line interface for the Ownkube developer platform"
  homepage "https://github.com/ownkube/ownkube-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ownkube/ownkube-cli/releases/download/v0.2.0/ownkube-cli_darwin_amd64.tar.gz"
      sha256 "529862a81761d456b4cd6bdc0191dcaf7387032616dff50f071f8a61ee83a140"

      define_method(:install) do
        bin.install "okctl"
        generate_completions_from_executable(bin/"okctl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ownkube/ownkube-cli/releases/download/v0.2.0/ownkube-cli_darwin_arm64.tar.gz"
      sha256 "8f0af29072d2fead43d91c2f881438198ef148c4ee38d9dcf4d3ca86bd33e88e"

      define_method(:install) do
        bin.install "okctl"
        generate_completions_from_executable(bin/"okctl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ownkube/ownkube-cli/releases/download/v0.2.0/ownkube-cli_linux_amd64.tar.gz"
      sha256 "a2a3e7bd9b6d2a75a5ee0205a7b70f0115c729e1db6e2230839b519593a4664f"
      define_method(:install) do
        bin.install "okctl"
        generate_completions_from_executable(bin/"okctl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ownkube/ownkube-cli/releases/download/v0.2.0/ownkube-cli_linux_arm64.tar.gz"
      sha256 "bc022c6ab8b6341a511f2584c79345fb04a148b1ab286a572bb9b3d7c8fe0c3f"
      define_method(:install) do
        bin.install "okctl"
        generate_completions_from_executable(bin/"okctl", "completion")
      end
    end
  end

  test do
    system "#{bin}/okctl", "version"
  end
end
