# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Okctl < Formula
  desc "Command-line interface for the Ownkube developer platform"
  homepage "https://github.com/ownkube/ownkube-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ownkube/ownkube-cli/releases/download/v0.3.0/ownkube-cli_darwin_amd64.tar.gz"
      sha256 "d9f084fe1b4b75b1429a753aa2da122b0531451d1a938716d2181bc117a09def"

      define_method(:install) do
        bin.install "okctl"
        generate_completions_from_executable(bin/"okctl", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ownkube/ownkube-cli/releases/download/v0.3.0/ownkube-cli_darwin_arm64.tar.gz"
      sha256 "49e10ece4dc88f9dd8ffd4efd679a8a364558f63cc2d36c04cda2153efa358d4"

      define_method(:install) do
        bin.install "okctl"
        generate_completions_from_executable(bin/"okctl", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ownkube/ownkube-cli/releases/download/v0.3.0/ownkube-cli_linux_amd64.tar.gz"
      sha256 "ce3d53d72902cf69dd9b5114a3919c9a603e9a07c06d94dab438a2b18714604a"
      define_method(:install) do
        bin.install "okctl"
        generate_completions_from_executable(bin/"okctl", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ownkube/ownkube-cli/releases/download/v0.3.0/ownkube-cli_linux_arm64.tar.gz"
      sha256 "33f4ed7ccf80287f855fb4d582614bef683895349b99206d67d54e46e49f14df"
      define_method(:install) do
        bin.install "okctl"
        generate_completions_from_executable(bin/"okctl", "completion")
      end
    end
  end

  test do
    system "#{bin}/okctl", "version"
  end
end
